### ISSUE TITLE
primitive type added a dot

### ISSUE THREAD

**Issue by jesperbrasmussen** [vardars/dotize#1]
Nice work.
I found a little error in you code.
You are missing a check for if prefix is not defined in line 21 like you do all the other places in the code. This error causes a dot to be added to the beginning of a property name of a primitive type when no prefix is supplied.

The line should look like this:
newobj[(p ? p + "." : "") + f] = o[f]; // primitive

**Comment by vardars** [comment]
thanks for pointing out.

Fixed with commit: 
https://github.com/vardars/dotize/commit/43107d9ce0ee10c7c04861bad8170b112b33b2e2#diff-4334a19297191c33e13362a0aa124ee7
