### ISSUE TITLE
arrays should have a consistant notation

### ISSUE THREAD

**Issue by avnr** [vardars/dotize#4]
```
dotize.convert([])   ==> {  } // expect: [] ???
dotize.convert([],"foo") ==> {  } // expect: {foo:[]} ???
OKAY!: dotize.convert(["foo"]) ==> {0:"foo"}
OKAY!: dotize.convert(["foo"],"foo") ==> {foo.0:"foo"}

dotize.convert([[[{foo:"one"}],[{foo:"two"}]],[[{foo:"three"}],[{foo:"four"}]]]) ==>
    { 0.0[0].foo: "one", 0.1[0].foo: "two", 1.0[0].foo: "three", 1.1[0].foo: "four" }
    // expect: { 0.0.0.foo: "one", 0.1.0.foo: "two", 1.0.0.foo: "three", 1.1.0.foo: "four" }
```

**Comment by vardars** [comment]
I added further support for arrays and inconsistent notation, and also tests including them.

**Comment by vardars** [comment]
by the way 
dotize.convert([[[{"foo":"one"}],[{"foo":"two"}]],[[{"foo":"three"}],[{"foo":"four"}]]])
V
{ "[0][0][0].foo": "one", "[0][1][0].foo": "two", "[1][0][0].foo": "three", "[1][1][0].foo": "four" }
is more appropiate imo.

**Comment by avnr** [comment]
Well done!

The {" [_n_]": ...}  notation indeed makes sense as it allows to reconstruct the original object into an array.

The solution still doesn't recognize [] as different from {}. While my suggestion isn't consistent with the notation of non-empty arrays, it _is_ consistent with the notation for free-standing keywords, numbers and strings.

**Comment by vardars** [comment]
I added empty Array support.
dotize.convert([]) 
returns 
[]

Thanks again.
